### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [wulfeku3/week10#1]
This is looking very good, except for one thing. I do see some inconsistent indentation and some hard-tabs throughout the project. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by wulfeku3** [comment]
When I tried reconfiguring sublime text it gave me this error:

"Error trying to parse settings: Unexpected trailing characters in C:\Users\Erika\AppData\Roaming\Sublime Text 2\Packages\User\Preferences.sublime-settings:5:1"

Because of this it wouldn't let me save the preferences file. Any advice?

**Comment by chrisvfritz** [comment]
Does this page https://www.sublimetext.com/forum/viewtopic.php?f=3&t=6633
help? If not, I should be able to figure out what's wrong if you send me
your settings file.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by wulfeku3** [comment]
Okay, I think(???) this one is fixed now too, but my own repo confuses me. :( Please let me know!

**Comment by chrisvfritz** [comment]
Yeah, we definitely need to fix this repo. My guess is you initialized a git repo in the directory for _all_ your projects, then got an error when trying to `git push origin master` and "fixed" it with `git push origin master -f`, which overrode what you had before. If this is what happened, just FYI, one should _never_ force a push to GitHub unless you know exactly what you're doing... otherwise stuff like this can happen. :-/

We can fix this, but it'll be a lot easier in real time. What do you think about tackling this together on Monday?

**Comment by wulfeku3** [comment]
I've never tried to force a push, so I have no idea how this disaster happened. Monday sounds good!

**Comment by wulfeku3** [comment]
Okay, FINALLY fixed (hopefully). Thanks for the help!

**Comment by chrisvfritz** [comment]
OK, the repo's back to a normal state, but I still see hard tabs here:

```
Searching 104 files for "\t" (regex)

app/assets/stylesheets/static.css:
    1  html {
    2:  background-color: #626262;
    3  }
    4  
    5  body {
    6:  width: 761px;
    7:  margin: 1.5em auto;
    8:  border-color: #999;
    9:  border-style: solid;
   10:  border-width: 10px;
   11:  padding: 50px;
   12:  padding-top:10px;
   13:  background-color:#727071;
   14:  
   15  }
   16  
   17  h1 {
   18:  text-align: center;
   19:  color: #420842;
   20:  background-color: #626262;
   21:  margin:15px;
   22:  font-family:sans-serif;
   23  }
   24  
   25  p {
   26:  font-family: sans-serif;
   27  }
   28  
   29  a {
   30:  font-weight: bold;
   31:  text-decoration: underline;
   32:  color: #6a006a;
   33:  font-family: sans-serif;
   34  }
   35  
   36  a:hover {
   37:  font-weight: bold;
   38:  text-decoration: underline;
   39:  color: #f2a400;
   40  }
   41  
   42  :visited {
   43:  color:#191919;
   44  }
   45  
   46  a:active {
   47:  background-color: #727071;
   48  }
```

**Comment by wulfeku3** [comment]
No wonder I didn't find those--I haven't touched that file in ages. Should be fixed! Please tell me those were the last ones.

**Comment by chrisvfritz** [comment]
You betcha. :+1: :smiley:
